setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('desire_moda_feminina.urls')),
    path('vestidos/', include('vestidos.urls')),
    path('blusas/', include('blusas.urls')),
    path('calcas/', include('calcas.urls')),
    path('roupa_intima/', include('roupa_intima.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vestidos/urls.py
from django.urls import path
from vestidos.views import vestidos, adicionar_vestido, editar_vestido, excluir_vestido, detalhes_vestido

urlpatterns = [
    path('vestidos/', vestidos, name='vestidos'),
    path('adicionar_vestido/', adicionar_vestido, name='adicionar_vestido'),
    path('vestido/<int:id>/', detalhes_vestido, name='detalhes_vestido'),
    path('vestido/<int:id>/editar/', editar_vestido, name='editar_vestido'),
    path('vestido/<int:id>/excluir/', excluir_vestido, name='excluir_vestido'),
]

vestidos/models.py
from django.db import models

class Vestido(models.Model):
    CORES_CHOICES = [
        ('AZ', 'Azul'),
        ('VM', 'Vermelho'),
        ('PR', 'Preto'),
        ('BR', 'Branco'),
        ('AM', 'Amarelo'),
    ]
    
    TAMANHOS_CHOICES = [
        ('PP', 'Extra Pequeno'),
        ('P', 'Pequeno'),
        ('M', 'Médio'),
        ('G', 'Grande'),
        ('GG', 'Extra Grande'),
    ]

    nome = models.CharField('Nome do Produto:', null=False, blank=False, max_length=70)
    preco = models.CharField('Preço:', null=False, blank=False, max_length=10)
    detalhes = models.TextField('Detalhes do Produto:', null=True, blank=True)
    quantidade_estoque = models.IntegerField('Quantidade em Estoque:', default=0)
    cor = models.CharField('Cor:', max_length=2, choices=CORES_CHOICES, default='AZ')
    tamanho = models.CharField('Tamanho:', max_length=2, choices=TAMANHOS_CHOICES, default='M')
    imagem = models.ImageField('Imagem do Produto:', upload_to='produtos/', null=True, blank=True)

    def __str__(self):
        return f'{self.nome}'

vestidos/forms.py
from django import forms
from .models import Vestido



class VestidoForm(forms.ModelForm):
    class Meta:
        model = Vestido
        fields = ['nome', 'preco', 'detalhes', 'cor', 'tamanho', 'imagem', 'quantidade_estoque']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Produto'}),
            'preco': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Preço'}),
            'detalhes': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Detalhes do Produto'}),
            'cor': forms.Select(attrs={'class': 'form-select'}),
            'tamanho': forms.Select(attrs={'class': 'form-select'}),
            'quantidade_estoque': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Quantidade em Estoque'}),
        }

vestidos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import VestidoForm
from .models import Vestido
from django.core.paginator import Paginator


def vestidos(request):
    vestidos_disponiveis = Vestido.objects.filter(quantidade_estoque__gt=0)
    paginator = Paginator(vestidos_disponiveis, 15)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    return render(request, 'vestidos/vestidos.html', {'vestidos': vestidos_disponiveis, 'page_obj': page_obj})

def adicionar_vestido(request):
    if request.method == 'POST':
        form = VestidoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('administrativo')
    else:
        form = VestidoForm()
    return render(request, 'vestidos/adicionar_vestido.html', {'form': form})


def detalhes_vestido(request, id):
    vestido = get_object_or_404(Vestido, id=id)
    return render(request, 'vestidos/detalhes_vestido.html', {'vestido': vestido})

def editar_vestido(request, id):
    vestido = get_object_or_404(Vestido, id=id)
    if request.method == 'POST':
        form = VestidoForm(request.POST, request.FILES, instance=vestido)
        if form.is_valid():
            form.save()
            return redirect('administrativo')
    else:
        form = VestidoForm(instance=vestido)
    return render(request, 'vestidos/editar_vestido.html', {'form': form})



def excluir_vestido(request, id):
    vestido = get_object_or_404(Vestido, id=id)
    vestido.delete()
    return redirect('administrativo')

templates/vestidos/adicionar_vestido.html
{% extends 'desire_moda_feminina/base.html' %}
{% load static %}
{% block content %}
<style>
    label {
        font-weight: bold;
        color: black;
    }
</style>

<section class="container">
    {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <br><br>
    <h1 class="text-center fw-bolder ">Adicionar Vestido</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="contact-button" type="submit">Salvar</button>
    </form>
</section>
<br><br>

{% endblock %}

templates/vestidos/detalhes_vestido.html
{% extends 'desire_moda_feminina/base.html' %}
{% load static %}
{% block content %}
<style>
    .card {
        display: flex;
        flex-direction: row;
        align-items: stretch;
        border: none;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        overflow: hidden;
    }
    .card-body {
        background-color: #0e2b0d;
        color: white;
        flex: 1;
        padding: 40px;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    .card-img-left {
        flex: 0 0 40%;
        max-width: 40%;
        overflow: hidden;
    }
    .card-img-left img {
        width: 100%;
        height: auto;
    }
    .btn-group {
        margin-top: 20px;
    }
    .contact-button {
        background-color: #ffffff;
        color: #0e2b0d;
        border: none;
        margin-right: 10px;
        border: 2px solid #dcae51;
    }
    .contact-button:hover {
        background-color: white;
        border: 4px solid #dcae51;
        color: black;
    }
</style>

<section class="p-5">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8 mb-4"> <!-- Ajusta a largura da coluna -->
                <div class="card">
                    <div class="card-img-left">
                        {% if vestido.imagem %}
                            <img src="{{ vestido.imagem.url }}" alt="Imagem de {{ vestido.nome }}">
                        {% else %}
                            <img src="https://via.placeholder.com/150" alt="Imagem não disponível">
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ vestido.nome }}</h5>
                        <p class="card-text">Preço: {{ vestido.preco }}</p>
                        <p class="card-text">Cor: {{ vestido.get_cor_display }}</p>
                        <p class="card-text">Tamanho: {{ vestido.get_tamanho_display }}</p>
                        <p class="card-text">Detalhes: {{ vestido.detalhes }}</p>
                        <p class="card-text">Quantidade em Estoque: {{ vestido.quantidade_estoque }}</p>
                        <div class="btn-group">
                           <a href="{% url 'adicionar_ao_carrinho' vestido.id 'Vestido' %}" class="btn contact-button">Adicionar ao Carrinho</a>


                            <a href="#" class="btn contact-button">Comprar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/vestidos/editar_vestido.html
{% extends 'desire_moda_feminina/base.html' %}
{% load static %}
{% block content %}
<style>
    label {
        font-weight: bold; 
        color: black; 
    }
</style>


<section class="p-5 container">
    <h2  class="text-center fw-bolder">Editar conteúdo</h2>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn contact-button mr-2" type="submit">Salvar alterações</button>
        <a href="{% url 'vestidos' %}" class="btn contact-button">Cancelar</a>

    </form>
</section>                     
{% endblock %}

templates/vestidos/vestidos.html
{% extends 'desire_moda_feminina/base.html' %}
{% load static %}
{% block content %}
<style>
    .card {
        border: none;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        overflow: hidden;
        margin-bottom: 20px;
    }
  
.card img {
    width: 100%;
    height: 200px; /* Define uma altura fixa */
    object-fit: contain; /* Ajusta a imagem para caber completamente no espaço, mantendo as proporções */
    background-color: #f0f0f0; /* Define uma cor de fundo para preencher quaisquer espaços vazios */
}

    .card-body {
        background-color: #0e2b0d;
        color: white;
        padding: 20px;
        text-align: center;
    }
    .btn-group {
        margin-top: 15px;
    }
    .card-botao, .btn-warning, .btn-danger {
        border: none;
        margin-right: 5px;
        border: 2px solid #dcae51;
        color: #eef0ee;
        text-transform: uppercase;
        transition: all 0.3s;
    }
    .card-botao:hover, .btn-warning:hover, .btn-danger:hover {
        background-color: white;
        border: 4px solid #dcae51;
        color: black;
    }

</style>

<section class="p-5 container">
<h2 class="text-center fw-bolder p-5">Vestidos</h2>
    <div class="container mt-4">
        <div class="row">
            {% for vestido in page_obj %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if vestido.imagem %}
                            <img src="{{ vestido.imagem.url }}" alt="Imagem de {{ vestido.nome }}">
                        {% else %}
                            <img src="https://via.placeholder.com/150" alt="Imagem não disponível">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ vestido.nome }}</h5>
                            <p class="card-text">Preço: {{ vestido.preco }}</p>
                            <div class="btn-group">
                                <a href="{% url 'detalhes_vestido' vestido.id %}" class="btn card-botao">Detalhes</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p class="text-center">Nenhum vestido disponível no momento.</p>
            {% endfor %}
        </div>
    </div>

    <!-- Controle de Paginação -->
    <div class="mt-4">
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            <li class="page-item disabled">
                <a class="page-link">{{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
          </ul>
        </nav>
    </div>
</section>




<section class="p-5">
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn contact-button">Logout</button>
    </form>
</div>
</section>


{% endblock %}